CREATE TABLE IF NOT EXISTS `table_of_contents` (
  `id` VARCHAR(36) PRIMARY KEY,
  `ebook_id` VARCHAR(36) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `page_number` SMALLINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`id`) REFERENCES `ebooks`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;