name: Database Migration

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/

      - name: Run migrations
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          echo "Running database migrations..."
          migrate -path ./migrations -database "$DB_URL" up
          echo "Migrations completed successfully!"

      - name: Verify migration status
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          echo "Checking migration status..."
          migrate -path ./migrations -database "$DB_URL" version 